[package]
name = "tuwien-geo-masterthesis"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["Niko Pikall"]
license = "MIT"
description = "The official template for Mastertheses at the Geo Department of TU Wien."
repository = "https://github.com/TUW-GEO/tuwien-geo-masterthesis.git"
keywords = ["template", "article"]
categories = ["thesis"]
disciplines = [
	"biology",
	"chemistry",
	"computer-science",
	"engineering",
	"geography",
	"mathematics",
	"physics",
]
compiler = "0.14.0"
exclude = [".github", "docs", "scripts", "tests", ".typstignore", "Justfile"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
